// Generated by scripts/build-adapter.mjs; fingerprint of adapter sources.
const TUNNAL_P0_BUILD = 'e9cb16e1fd7cdcaea34112b9a0351637137e06fdf2ae95021dcd3e25021b7310';
/* P0 adapter: only pairing metadata is stored. No HUD settings or page data are read. */
(() => {
    const KEY = 'tunnalP0PairingV1';
    const ORIGIN = 'http://127.0.0.1:3491';
    const UUID = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
    let queue = Promise.resolve();
    function externalSender(sender) {
        return sender.url === ORIGIN + '/connector' && sender.origin === ORIGIN && Number.isInteger(sender.tab?.id) && sender.frameId === 0;
    }
    async function state() {
        const value = (await chrome.storage.session.get(KEY))[KEY];
        return value || {instanceId:crypto.randomUUID(), pairs:[]};
    }
    function prune(value) { value.pairs = value.pairs.filter(pair => pair.expiresAt > Date.now()); }
    const SETTINGS_CAPABILITIES = Object.freeze(['build.read', 'settings.read', 'settings.write']);
    const SETTINGS_ACTIONS = Object.freeze(['settings.read', 'settings.apply', 'operation.status']);
    function sameDocument(pair, sender) {
        return pair.documentId === undefined || sender.documentId === pair.documentId;
    }
    function operationId(value) { return UUID.test(value || ''); }
    function coordinator() { return globalThis.YtCdHudSettingsCoordinator; }
    async function external(message, sender) {
        if (!externalSender(sender) || !UUID.test(message.challenge || '')) return {ok:false,error:'SENDER_DENIED'};
        if (!['begin','read','revoke',...SETTINGS_ACTIONS].includes(message.action)) return {ok:false,error:'READ_ONLY'};
        const value = await state(); prune(value);
        let pair = value.pairs.find(item => item.tabId === sender.tab.id && item.challenge === message.challenge);
        if (message.action === 'begin') {
            if (message.mode !== undefined && message.mode !== 'settings' && message.mode !== 'p0') return {ok:false,error:'INVALID_MODE'};
            if (!pair) {
                value.pairs = value.pairs.filter(item => item.tabId !== sender.tab.id);
                if (value.pairs.length >= 5) return {ok:false,error:'PAIR_LIMIT'};
                const settingsMode = message.mode === 'settings';
                pair = {tabId:sender.tab.id,challenge:message.challenge,origin:ORIGIN,mode:settingsMode?'settings':'p0',
                    documentId:sender.documentId,requestedCapabilities:settingsMode?[...SETTINGS_CAPABILITIES]:['build.read'],
                    approvedCapabilities:[],approved:false,expiresAt:Date.now()+120_000};
                value.pairs.push(pair);
                await chrome.storage.session.set({[KEY]:value});
            } else if ((message.mode === 'settings') !== (pair.mode === 'settings')) {
                return {ok:false,error:'PAIR_MODE_MISMATCH'};
            }
            return {ok:true,status:pair.approved?'PAIRED':'PENDING'};
        }
        if (!pair) return {ok:false,error:'PAIR_REQUIRED'};
        if (!sameDocument(pair,sender)) return {ok:false,error:'SENDER_DENIED'};
        if (message.action === 'revoke') {
            value.pairs = value.pairs.filter(item => item !== pair);
            await chrome.storage.session.set({[KEY]:value});
            return {ok:true,status:'REVOKED'};
        }
        if (!pair.approved) return {ok:true,status:'PENDING'};
        const approvedCapabilities = pair.approvedCapabilities || ['build.read'];
        if (message.action === 'read') return {ok:true,report:{extensionId:chrome.runtime.id,version:chrome.runtime.getManifest().version,adapterBuild:TUNNAL_P0_BUILD,instanceId:value.instanceId,challenge:pair.challenge,pairedUntil:pair.expiresAt,capabilities:[...approvedCapabilities]}};
        if (pair.mode !== 'settings' || !approvedCapabilities.includes('settings.read')) return {ok:false,error:'CAPABILITY_DENIED'};
        if (message.expectedBuild !== TUNNAL_P0_BUILD) return {ok:false,error:'BUILD_MISMATCH'};
        if (!operationId(message.operationId)) return {ok:false,error:'INVALID_OPERATION'};
        const api = coordinator();
        if (!api || typeof api.execute !== 'function') return {ok:false,error:'COORDINATOR_UNAVAILABLE'};
        if (message.action === 'settings.apply' && !approvedCapabilities.includes('settings.write')) return {ok:false,error:'CAPABILITY_DENIED'};
        const result = await api.execute({action:message.action === 'settings.apply' ? 'apply' : message.action === 'operation.status' ? 'operation.status' : 'read',operationId:message.operationId,baseRevision:message.baseRevision,payload:message.payload});
        if (!result || typeof result !== 'object' || typeof result.ok !== 'boolean') return {ok:false,error:'COORDINATOR_INVALID_RESPONSE'};
        return result.ok ? {ok:true,...result} : result;
    }
    async function internal(message, sender) {
        if(sender.id !== chrome.runtime.id || sender.url !== chrome.runtime.getURL('tunnal/pair.html')) return {ok:false,error:'PAIR_UI_REQUIRED'};
        const value = await state(); prune(value);
        if(message.action === 'list') return {ok:true,adapterBuild:TUNNAL_P0_BUILD,pairs:value.pairs.map(({challenge,origin,mode,requestedCapabilities,approvedCapabilities,approved,expiresAt})=>({challenge,origin,mode,requestedCapabilities,approvedCapabilities,approved,expiresAt}))};
        if(message.action === 'revokeAll') { value.pairs = []; await chrome.storage.session.set({[KEY]:value}); return {ok:true}; }
        if(!['approve','approveSettings'].includes(message.action) || !UUID.test(message.challenge || '')) return {ok:false,error:'ACTION_DENIED'};
        const pair = value.pairs.find(item => item.challenge === message.challenge);
        if(!pair) return {ok:false,error:'PAIR_EXPIRED'};
        // Revalidate the connector tab at approval time rather than trusting a stale pending request.
        const tab = await chrome.tabs.get(pair.tabId);
        // URL may be hidden without tabs permission. The external handler always checks the full URL again on read.
        if(!tab || (tab.url && tab.url !== ORIGIN+'/connector')) return {ok:false,error:'CONNECTOR_GONE'};
        if (message.action === 'approveSettings' && (pair.mode !== 'settings' || pair.approved || JSON.stringify(pair.requestedCapabilities) !== JSON.stringify(SETTINGS_CAPABILITIES))) return {ok:false,error:'PAIR_MODE_MISMATCH'};
        if (message.action === 'approve' && (pair.mode === 'settings' || pair.approved)) return {ok:false,error:pair.mode === 'settings'?'SETTINGS_APPROVAL_REQUIRED':'ALREADY_APPROVED'};
        pair.approved = true; pair.approvedCapabilities = message.action === 'approveSettings' ? [...SETTINGS_CAPABILITIES] : ['build.read']; pair.expiresAt = Date.now()+15*60_000;
        await chrome.storage.session.set({[KEY]:value});
        return {ok:true,status:'PAIRED'};
    }
    function listen(handler) {
        return (message,sender,reply) => {
            if(message?.type !== 'TUNNAL_P0') return false;
            queue = queue.then(async()=>{ try { reply(await handler(message,sender)); } catch { reply({ok:false,error:'ADAPTER_ERROR'}); } });
            return true;
        };
    }
    chrome.runtime.onMessageExternal.addListener(listen(external));
    chrome.runtime.onMessage.addListener(listen(internal));
})();
